spring.application.name=main
    spring.datasource.url=jdbc:postgresql://localhost:5432/retail_db
spring.datasource.username=postgres
spring.datasource.password=yournewpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081